spring.application.name=cic

spring.datasource.url=jdbc:postgresql://localhost:5433/cic-intranet
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

file.upload-dir.documents=uploads/documents
file.upload-dir.images=uploads/images
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.task.scheduling.enabled=true

CORS_ALLOWED_ORIGINS=http://localhost:5173,https://cicintranet.netlify.app/

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# Auth
auth.validator.type=stem-link
jwt.secret=your-very-long-secret-key-at-least-32-characters-long

# Use the same secret for issuing tokens in AuthServiceImpl
app.jwt.secret=${jwt.secret}
app.jwt.expiration-ms=28800000
