spring.application.name=cic

spring.profiles.active=prod

# Local PostgreSQL Docker container
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/cic}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123Thineth//}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.qjxxgurmxbbncjebrpgq.supabase.co:5432/}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123Thineth//}


# File upload local storage

file.upload-dir=${FILE_UPLOAD_DIR:/uploads}
app.base-url=${APP_BASE_URL:http://192.168.120.10}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB



# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.task.scheduling.enabled=true

# CORS
CORS_ALLOWED_ORIGINS=http://localhost:5173,http://192.168.120.10,https://cicintranet.netlify.app
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
#bb

# Auth
auth.validator.type=stem-link
jwt.secret=${JWT_KEY:+HwowrjQMtglDblAqTYbNnKplz1ZQvS3xGudEQuMCNt0lddoL7fx9f5b61h4X7qkh0mkEvzrMw3XkHL7nmyroQ==}
audit.log.retention-hours=96
app.jwt.secret=${jwt.secret}
app.jwt.expiration-ms=28800000

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL:info.cicfeedsgrp@gmail.com}
spring.mail.password=${PASSWORD:zhmbjpffmbiuaixa}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Ticket URL
app.ticket.url=http://192.168.120.10/admin/ticket

# superuser
app.superuser.email=${SEND_EMAIL:hasan@cicfeeds.lk,gayan@cicfeeds.lk,masterdata@cicfeeds.lk}