spring.application.name=cic

spring.profiles.active=prod

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/cic-intranet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Local with Docker
# ---
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/cic-intranet}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}


#file.upload-dir.documents=uploads/documents
#file.upload-dir.images=uploads/images
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Remove old local dir configs, replace with:
gcs.bucket-name=my-intranet-files
gcs.credentials-path=${CREDENTIAL_PATH:classpath:gcs-credentials.json}

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.task.scheduling.enabled=true

CORS_ALLOWED_ORIGINS=http://localhost:5173,https://cicintranet.netlify.app/

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# Auth
auth.validator.type=stem-link
jwt.secret=your-very-long-secret-key-at-least-32-characters-long

# Use the same secret for issuing tokens in AuthServiceImpl
app.jwt.secret=${jwt.secret}
app.jwt.expiration-ms=28800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL:info.cicfeedsgrp@gmail.com}
spring.mail.password=${PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#info.cicfeedsgrp@gmail.com
#zhmbjpffmbiuaixa
app.ticket.url=http://localhost:5173/admin/ticket

# Super user email to notify
app.superuser.email=${SEND_EMAIL:gayan@cicfeeds.lk,hasan@cicfeeds.lk, masterdata@cicfeeds.lk}
