spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

file.upload-dir.documents=uploads/documents
file.upload-dir.images=uploads/images
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

